# -*- coding: utf-8 -*-

from enum import Enum


class Cms_Enum(Enum):
    '''各种cms的枚举类型和说明'''
    joomla = "joomla"
    phpcms = "phpcms"
    dedecms = "dedecms"
    seacms = "seacms"
    discuz = "discuz"
    acsoft = "acsoft"
    cmseasy = "cmseasy"
    dreamgallery = "dreamgallery"
    ecshop = "ecshop"
    eyou = "eyou"
    fastmeeting = "fastmeeting"
    finecms = "finecms"
    FoosunCms = "FoosunCms"
    fsmcms = "fsmcms"
    gowinsoft_jw = "gowinsoft_jw"
    hanweb = "hanweb"
    kxmail = "kxmail"
    libsys = "libsys"
    metinfo = "metinfo"
    pageadmin = "pageadmin"
    phpok = "phpok"
    piaoyou = "piaoyou"
    qibocms = "qibocms"
    shopex = "shopex"
    shopnc = "shopnc"
    siteengine = "siteengine"
    siteserver = "siteserver"
    thinkphp = "thinkphp"
    thinksns = "thinksns"
    typecho = "typecho"
    umail = "umail"
    urp = "urp"
    weaver_oa = "weaver_oa"
    wecenter = "wecenter"
    wordpress = "wordpress"
    xplus = "xplus"
    zfsoft = "zfsoft"
    zuitu = "zuitu"
